//! Command implementations for the Radium CLI.

pub mod agents;
pub mod auth;
pub mod autonomous;
pub mod batch;
pub mod secret;
pub mod braingrid;
pub mod budget;
pub mod capability;
pub mod chat;
pub mod checkpoint;
pub mod clean;
pub mod clipboard;
pub mod code;
pub mod complete;
pub mod context;
pub mod cost;
pub mod craft;
pub mod custom;
pub mod doctor;
pub mod engines;
pub mod extension;
pub mod hooks;
pub mod init;
pub mod models;
pub mod mcp;
pub mod mcp_proxy;
pub mod monitor;
pub mod plan;
pub mod policy;
pub mod constitution;
pub mod requirement;
pub mod run;
pub mod sandbox;
pub mod session;
pub mod stats;
pub mod status;
pub mod step;
pub mod templates;
pub mod learning;
pub mod playbook;
pub mod types;
pub mod validate;
pub mod vibecheck;
pub mod privacy;
pub mod theme;
pub mod tool_execution;
pub mod tools;
pub mod train;
pub mod event_renderer;

// Re-export types for convenience
pub use types::{AgentsCommand, AuthCommand, EnginesCommand, ExtensionCommand, ToolsCommand};
pub use types::{CustomCommand, TemplatesCommand, BraingridCommand, CacheCommand, SecretCommand};
pub use types::{TrainCommand, AwsTrainCommand};
pub use context::ContextCommand;
pub use budget::BudgetCommand;
pub use constitution::ConstitutionCommand;
