//! TypeScript state management code generator
//!
//! Generates type-safe TypeScript code for workflow state management,
//! including interfaces, getters/setters, and snapshot utilities.

use handlebars::Handlebars;
use serde::Serialize;

use crate::schema::variables::VariableDefinition;

/// State code generator
pub struct StateGenerator<'a> {
    handlebars: &'a Handlebars<'a>,
}

/// Context for state template rendering
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StateTemplateContext {
    /// Workflow name (used for type names)
    pub workflow_name: String,
    /// All variables
    pub variables: Vec<VariableTemplateData>,
    /// Input variables (required)
    pub input_variables: Vec<VariableTemplateData>,
    /// Output variables
    pub output_variables: Vec<VariableTemplateData>,
    /// Generated at timestamp
    pub generated_at: String,
}

/// Variable data for templates
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VariableTemplateData {
    /// Variable name
    pub name: String,
    /// TypeScript type
    pub typescript_type: String,
    /// Default value as TypeScript code
    pub default_value: String,
    /// Whether the variable is required
    pub is_required: bool,
    /// Whether the variable can be null
    pub is_nullable: bool,
    /// Optional description
    pub description: Option<String>,
}

impl<'a> StateGenerator<'a> {
    /// Create a new state generator
    pub fn new(handlebars: &'a Handlebars<'a>) -> Self {
        Self { handlebars }
    }

    /// Generate state management TypeScript code
    pub fn generate(&self, context: &StateTemplateContext) -> Result<String, StateGenError> {
        self.handlebars
            .render("state", context)
            .map_err(|e| StateGenError::TemplateError(e.to_string()))
    }

    /// Build template context from variable definitions
    pub fn build_context(
        workflow_name: &str,
        definitions: &[VariableDefinition],
    ) -> StateTemplateContext {
        let variables: Vec<VariableTemplateData> = definitions
            .iter()
            .map(|d| VariableTemplateData {
                name: d.name.clone(),
                typescript_type: d.variable_type.to_typescript().to_string(),
                default_value: d.variable_type.default_value_ts().to_string(),
                is_required: d.required,
                is_nullable: d.is_nullable(),
                description: d.description.clone(),
            })
            .collect();

        let input_variables: Vec<VariableTemplateData> = variables
            .iter()
            .filter(|v| v.is_required)
            .cloned()
            .collect();

        StateTemplateContext {
            workflow_name: workflow_name.to_string(),
            variables,
            input_variables,
            output_variables: Vec::new(),
            generated_at: chrono::Utc::now().to_rfc3339(),
        }
    }

    /// Generate inline (without template) for simple cases
    pub fn generate_inline(
        workflow_name: &str,
        definitions: &[VariableDefinition],
    ) -> Result<String, StateGenError> {
        let context = Self::build_context(workflow_name, definitions);
        let mut code = String::new();

        // Header
        code.push_str(&format!(
            "// Generated by Radium Workflow Compiler - DO NOT EDIT\n"
        ));
        code.push_str(&format!("// Workflow: {}\n", context.workflow_name));
        code.push_str(&format!("// Generated at: {}\n\n", context.generated_at));

        // Input interface
        code.push_str(&format!(
            "/**\n * Input type for {}\n */\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "export interface {}Input {{\n",
            context.workflow_name
        ));
        for var in &context.input_variables {
            if let Some(desc) = &var.description {
                code.push_str(&format!("  /** {} */\n", desc));
            }
            let optional = if var.is_required { "" } else { "?" };
            let nullable = if var.is_nullable { " | null" } else { "" };
            code.push_str(&format!(
                "  {}{}: {}{};\n",
                var.name, optional, var.typescript_type, nullable
            ));
        }
        code.push_str("}\n\n");

        // Output interface
        code.push_str(&format!(
            "/**\n * Output type for {}\n */\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "export interface {}Output {{\n",
            context.workflow_name
        ));
        for var in &context.output_variables {
            if let Some(desc) = &var.description {
                code.push_str(&format!("  /** {} */\n", desc));
            }
            let nullable = if var.is_nullable { " | null" } else { "" };
            code.push_str(&format!(
                "  {}: {}{};\n",
                var.name, var.typescript_type, nullable
            ));
        }
        code.push_str("}\n\n");

        // State interface
        code.push_str(&format!(
            "/**\n * State container for {}\n */\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "export interface {}State {{\n",
            context.workflow_name
        ));
        code.push_str(&format!("  input: {}Input;\n", context.workflow_name));
        code.push_str(&format!(
            "  output: Partial<{}Output>;\n",
            context.workflow_name
        ));
        code.push_str("  variables: {\n");
        for var in &context.variables {
            let nullable = if var.is_nullable { " | null" } else { "" };
            code.push_str(&format!(
                "    {}: {}{};\n",
                var.name, var.typescript_type, nullable
            ));
        }
        code.push_str("  };\n");
        code.push_str("  metadata: {\n");
        code.push_str("    workflowId: string;\n");
        code.push_str("    version: number;\n");
        code.push_str("    createdAt: Date;\n");
        code.push_str("    updatedAt: Date;\n");
        code.push_str("  };\n");
        code.push_str("}\n\n");

        // Create function
        code.push_str(&format!(
            "/**\n * Create initial state for {}\n */\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "export function create{}State(\n",
            context.workflow_name
        ));
        code.push_str("  workflowId: string,\n");
        code.push_str(&format!(
            "  input: {}Input\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "): {}State {{\n",
            context.workflow_name
        ));
        code.push_str("  const now = new Date();\n");
        code.push_str("  return {\n");
        code.push_str("    input,\n");
        code.push_str("    output: {},\n");
        code.push_str("    variables: {\n");
        for var in &context.variables {
            if var.is_required {
                code.push_str(&format!("      {}: input.{},\n", var.name, var.name));
            } else {
                code.push_str(&format!(
                    "      {}: {},\n",
                    var.name, var.default_value
                ));
            }
        }
        code.push_str("    },\n");
        code.push_str("    metadata: {\n");
        code.push_str("      workflowId,\n");
        code.push_str("      version: 1,\n");
        code.push_str("      createdAt: now,\n");
        code.push_str("      updatedAt: now,\n");
        code.push_str("    },\n");
        code.push_str("  };\n");
        code.push_str("}\n\n");

        // Getter function
        code.push_str(&format!(
            "/**\n * Type-safe variable getter\n */\n"
        ));
        code.push_str(&format!(
            "export function getVariable<K extends keyof {}State['variables']>(\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "  state: {}State,\n",
            context.workflow_name
        ));
        code.push_str("  key: K\n");
        code.push_str(&format!(
            "): {}State['variables'][K] {{\n",
            context.workflow_name
        ));
        code.push_str("  return state.variables[key];\n");
        code.push_str("}\n\n");

        // Setter function
        code.push_str(&format!(
            "/**\n * Type-safe variable setter with immutable update\n */\n"
        ));
        code.push_str(&format!(
            "export function setVariable<K extends keyof {}State['variables']>(\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "  state: {}State,\n",
            context.workflow_name
        ));
        code.push_str("  key: K,\n");
        code.push_str(&format!(
            "  value: {}State['variables'][K]\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "): {}State {{\n",
            context.workflow_name
        ));
        code.push_str("  return {\n");
        code.push_str("    ...state,\n");
        code.push_str("    variables: {\n");
        code.push_str("      ...state.variables,\n");
        code.push_str("      [key]: value,\n");
        code.push_str("    },\n");
        code.push_str("    metadata: {\n");
        code.push_str("      ...state.metadata,\n");
        code.push_str("      version: state.metadata.version + 1,\n");
        code.push_str("      updatedAt: new Date(),\n");
        code.push_str("    },\n");
        code.push_str("  };\n");
        code.push_str("}\n\n");

        // Snapshot interface
        code.push_str(&format!(
            "/**\n * Snapshot type for continue-as-new\n */\n"
        ));
        code.push_str(&format!(
            "export interface {}Snapshot {{\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "  variables: {}State['variables'];\n",
            context.workflow_name
        ));
        code.push_str("  progress: {\n");
        code.push_str("    lastCompleted: string | undefined;\n");
        code.push_str("    iterations: Record<string, number>;\n");
        code.push_str("  };\n");
        code.push_str("  continuation: {\n");
        code.push_str("    originalWorkflowId: string;\n");
        code.push_str("    continuationCount: number;\n");
        code.push_str("    startedAt: Date;\n");
        code.push_str("    continuedAt: Date;\n");
        code.push_str("  };\n");
        code.push_str("}\n\n");

        // Create snapshot function
        code.push_str(&format!(
            "/**\n * Create snapshot for continue-as-new\n */\n"
        ));
        code.push_str(&format!(
            "export function createSnapshot(state: {}State): {}Snapshot {{\n",
            context.workflow_name, context.workflow_name
        ));
        code.push_str("  return {\n");
        code.push_str("    variables: { ...state.variables },\n");
        code.push_str("    progress: {\n");
        code.push_str("      lastCompleted: undefined,\n");
        code.push_str("      iterations: {},\n");
        code.push_str("    },\n");
        code.push_str("    continuation: {\n");
        code.push_str("      originalWorkflowId: state.metadata.workflowId,\n");
        code.push_str("      continuationCount: 0,\n");
        code.push_str("      startedAt: state.metadata.createdAt,\n");
        code.push_str("      continuedAt: new Date(),\n");
        code.push_str("    },\n");
        code.push_str("  };\n");
        code.push_str("}\n\n");

        // Restore from snapshot function
        code.push_str(&format!(
            "/**\n * Restore state from snapshot\n */\n"
        ));
        code.push_str(&format!(
            "export function restoreFromSnapshot(\n"
        ));
        code.push_str("  workflowId: string,\n");
        code.push_str(&format!(
            "  snapshot: {}Snapshot,\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "  input: {}Input\n",
            context.workflow_name
        ));
        code.push_str(&format!(
            "): {}State {{\n",
            context.workflow_name
        ));
        code.push_str("  return {\n");
        code.push_str("    input,\n");
        code.push_str("    output: {},\n");
        code.push_str("    variables: snapshot.variables,\n");
        code.push_str("    metadata: {\n");
        code.push_str("      workflowId,\n");
        code.push_str("      version: 1,\n");
        code.push_str("      createdAt: snapshot.continuation.startedAt,\n");
        code.push_str("      updatedAt: new Date(),\n");
        code.push_str("    },\n");
        code.push_str("  };\n");
        code.push_str("}\n");

        Ok(code)
    }
}

/// State generation errors
#[derive(Debug, Clone, thiserror::Error)]
pub enum StateGenError {
    #[error("Template error: {0}")]
    TemplateError(String),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::variables::VariableType;

    #[test]
    fn test_build_context() {
        let definitions = vec![
            VariableDefinition::new("userId", VariableType::String).required(),
            VariableDefinition::new("count", VariableType::Integer),
        ];

        let context = StateGenerator::build_context("TestWorkflow", &definitions);

        assert_eq!(context.workflow_name, "TestWorkflow");
        assert_eq!(context.variables.len(), 2);
        assert_eq!(context.input_variables.len(), 1);
        assert_eq!(context.input_variables[0].name, "userId");
    }

    #[test]
    fn test_variable_template_data() {
        let def = VariableDefinition::new("name", VariableType::String)
            .required()
            .with_description("User name");

        let context = StateGenerator::build_context("Test", &[def]);
        let var = &context.variables[0];

        assert_eq!(var.name, "name");
        assert_eq!(var.typescript_type, "string");
        assert!(var.is_required);
        assert_eq!(var.description, Some("User name".to_string()));
    }

    #[test]
    fn test_generate_inline() {
        let definitions = vec![
            VariableDefinition::new("userId", VariableType::String).required(),
            VariableDefinition::new("count", VariableType::Integer),
            VariableDefinition::new("items", VariableType::Array),
        ];

        let code = StateGenerator::generate_inline("OrderWorkflow", &definitions).unwrap();

        // Verify no 'any' type
        assert!(!code.contains(": any"), "Generated code contains 'any' type");

        // Verify interfaces
        assert!(code.contains("export interface OrderWorkflowInput"));
        assert!(code.contains("export interface OrderWorkflowState"));
        assert!(code.contains("export interface OrderWorkflowSnapshot"));

        // Verify functions
        assert!(code.contains("export function createOrderWorkflowState"));
        assert!(code.contains("export function getVariable"));
        assert!(code.contains("export function setVariable"));
        assert!(code.contains("export function createSnapshot"));
        assert!(code.contains("export function restoreFromSnapshot"));

        // Verify type safety
        assert!(code.contains("keyof OrderWorkflowState['variables']"));
    }

    #[test]
    fn test_nullable_variables() {
        let definitions = vec![
            VariableDefinition::new("optional", VariableType::String)
                .with_constraints(crate::schema::variables::VariableConstraints::new().nullable(true)),
        ];

        let code = StateGenerator::generate_inline("Test", &definitions).unwrap();

        assert!(code.contains("| null"));
    }

    #[test]
    fn test_no_any_type() {
        // Test with 'Any' type - should generate 'unknown', not 'any'
        let definitions = vec![
            VariableDefinition::new("data", VariableType::Any),
        ];

        let code = StateGenerator::generate_inline("Test", &definitions).unwrap();

        assert!(code.contains("unknown"));
        assert!(!code.contains(": any"));
    }
}
