//! TUI components for the enhanced workflow dashboard.
//!
//! This module provides reusable UI components for displaying workflow execution,
//! agent timelines, telemetry, logs, and checkpoints.

pub mod agent_timeline;
pub mod checkpoint_modal;
pub mod checkpoint_interrupt_modal;
pub mod command_confirmation_modal;
pub mod dialog;
pub mod diff_view;
pub mod error_panel;
pub mod execution_detail_view;
pub mod execution_history_view;
pub mod help_row;
pub mod hints_bar;
pub mod summary_view;
pub mod interactive_table;
pub mod logo;
pub mod log_viewer;
pub mod loop_indicator;
pub mod orchestrator_thinking_panel;
pub mod output_window;
pub mod process_panel;
pub mod fix_approval_modal;
pub mod progress_indicator;
pub mod requirement_progress_bar;
pub mod spinner;
pub mod status_footer;
pub mod status_icon;
pub mod task_list;
pub mod task_list_panel;
pub mod textarea;
pub mod telemetry_bar;
pub mod title_bar;
pub mod toast;
pub mod playbook_browser;
pub mod playbook_status;

pub use agent_timeline::AgentTimeline;
pub use checkpoint_modal::CheckpointModal;
pub use checkpoint_interrupt_modal::CheckpointInterruptModal;
pub use command_confirmation_modal::{CommandConfirmationModal, ConfirmationOutcome, ConfirmationRequest, render_command_confirmation};
pub use dialog::{Dialog, DialogChoice, DialogManager, render_dialog};
pub use diff_view::{DiffView, render_diff_view};
pub use error_panel::{ErrorPanel, ErrorAction, render_error_panel};
pub use execution_detail_view::{Action as ExecutionDetailAction, ExecutionDetailView};
pub use execution_history_view::{Action as ExecutionHistoryAction, ExecutionHistoryView, SortColumn};
pub use help_row::render_help_row;
pub use hints_bar::{HintsBar, Hint, render_hints_bar, render_hints_bar_with_state};
pub use summary_view::{Action as SummaryAction, SummaryView};
pub use interactive_table::InteractiveTable;
pub use logo::{render_logo, render_logo_compact};
pub use log_viewer::LogViewer;
pub use loop_indicator::LoopIndicator;
pub use orchestrator_thinking_panel::OrchestratorThinkingPanel;
pub use output_window::OutputWindow;
pub use process_panel::ProcessPanel;
pub use fix_approval_modal::{ApprovalAction, FixApprovalModal, render_fix_approval_modal};
pub use progress_indicator::{ProgressIndicator, ProgressType, render_progress_indicator};
pub use requirement_progress_bar::{render_requirement_progress, render_requirement_progress_new, render_inline_progress, render_inline_progress_new};
pub use spinner::{Spinner, SpinnerFrames};
pub use status_footer::{AppMode, StatusFooter};
pub use status_icon::{get_status_color, render_status_icon};
pub use task_list::{render_task_summary, TaskItem, TaskList};
pub use task_list_panel::TaskListPanel;
pub use telemetry_bar::TelemetryBar;
pub use title_bar::render_title_bar;
pub use toast::{Toast, ToastManager, ToastVariant, render_toasts, render_toasts_with_areas};
pub use playbook_browser::PlaybookBrowser;
pub use playbook_status::PlaybookStatus;
