//! Map-Reduce Pattern
//!
//! Parallel processing with aggregation:
//! - Map: Transform items in parallel
//! - Reduce: Aggregate results
//! - Support for batching and chunking
//! - Configurable parallelism

use serde::{Deserialize, Serialize};
use validator::Validate;

use super::WorkflowPattern;

/// Map-Reduce pattern for parallel processing with aggregation
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct MapReduceDefinition {
    /// Pattern name
    #[validate(length(min = 1))]
    pub name: String,

    /// Description
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Map configuration
    pub map: MapConfig,

    /// Reduce configuration
    pub reduce: ReduceConfig,

    /// Maximum concurrent mappers
    #[serde(default = "default_concurrency")]
    pub max_concurrency: usize,

    /// Batch size for chunking input
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<usize>,

    /// Whether to continue on map failures
    #[serde(default)]
    pub continue_on_failure: bool,
}

fn default_concurrency() -> usize {
    10
}

impl MapReduceDefinition {
    /// Create a new map-reduce definition
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            map: MapConfig::default(),
            reduce: ReduceConfig::default(),
            max_concurrency: default_concurrency(),
            batch_size: None,
            continue_on_failure: false,
        }
    }

    /// Set description
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Set map config
    pub fn with_map(mut self, map: MapConfig) -> Self {
        self.map = map;
        self
    }

    /// Set reduce config
    pub fn with_reduce(mut self, reduce: ReduceConfig) -> Self {
        self.reduce = reduce;
        self
    }

    /// Set max concurrency
    pub fn with_max_concurrency(mut self, max: usize) -> Self {
        self.max_concurrency = max;
        self
    }

    /// Set batch size
    pub fn with_batch_size(mut self, size: usize) -> Self {
        self.batch_size = Some(size);
        self
    }

    /// Allow failures
    pub fn continue_on_failure(mut self) -> Self {
        self.continue_on_failure = true;
        self
    }
}

impl WorkflowPattern for MapReduceDefinition {
    fn pattern_name(&self) -> &'static str {
        "MapReduce"
    }

    fn validate_pattern(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if self.max_concurrency == 0 {
            errors.push("Max concurrency must be greater than 0".to_string());
        }

        if let Some(batch_size) = self.batch_size {
            if batch_size == 0 {
                errors.push("Batch size must be greater than 0".to_string());
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    fn to_typescript(&self) -> String {
        let mut code = String::new();

        // Header
        code.push_str(&format!(
            r#"// Map-Reduce: {}
// {}
// Generated by Rust Workflow Compiler

import {{ proxyActivities }} from '@temporalio/workflow';

interface MapReduceResult<T> {{
  result: T;
  processedCount: number;
  failedCount: number;
  errors: Error[];
}}

/**
 * {}
 */
export async function {}MapReduce<TInput, TMapOutput, TReduceOutput>(
  items: TInput[]
): Promise<MapReduceResult<TReduceOutput>> {{
  const maxConcurrency = {};
  const errors: Error[] = [];
  let failedCount = 0;
"#,
            self.name,
            self.description.as_deref().unwrap_or("No description"),
            self.description.as_deref().unwrap_or(&self.name),
            to_pascal_case(&self.name),
            self.max_concurrency
        ));

        // Generate batching if configured
        if let Some(batch_size) = self.batch_size {
            code.push_str(&format!(
                r#"
  // Batch items
  const batchSize = {};
  const batches: TInput[][] = [];
  for (let i = 0; i < items.length; i += batchSize) {{
    batches.push(items.slice(i, i + batchSize));
  }}

  // Process batches
  const mapResults: TMapOutput[] = [];
  for (const batch of batches) {{
    const batchResults = await mapBatch(batch);
    mapResults.push(...batchResults);
  }}
"#,
                batch_size
            ));
        } else {
            code.push_str(
                r#"
  // Map phase - process items with concurrency control
  const mapResults: TMapOutput[] = [];
  const chunks: TInput[][] = [];

  for (let i = 0; i < items.length; i += maxConcurrency) {
    chunks.push(items.slice(i, i + maxConcurrency));
  }

  for (const chunk of chunks) {
    const chunkPromises = chunk.map(async (item, index) => {
      try {
"#,
            );

            code.push_str(&format!(
                "        return await {};\n",
                self.map.mapper.to_typescript()
            ));

            if self.continue_on_failure {
                code.push_str(
                    r#"      } catch (error) {
        errors.push(error as Error);
        failedCount++;
        return null;
      }
    });

    const results = await Promise.all(chunkPromises);
    mapResults.push(...results.filter((r): r is TMapOutput => r !== null));
  }
"#,
                );
            } else {
                code.push_str(
                    r#"      } catch (error) {
        throw error;
      }
    });

    const results = await Promise.all(chunkPromises);
    mapResults.push(...results);
  }
"#,
                );
            }
        }

        // Generate reduce phase
        code.push_str("\n  // Reduce phase\n");

        match &self.reduce.reducer {
            Reducer::Sum => {
                code.push_str("  const result = mapResults.reduce((acc, val) => acc + (val as number), 0) as TReduceOutput;\n");
            }
            Reducer::Concat => {
                code.push_str(
                    "  const result = mapResults.flat() as unknown as TReduceOutput;\n",
                );
            }
            Reducer::Merge => {
                code.push_str("  const result = mapResults.reduce((acc, val) => ({ ...acc, ...val }), {}) as TReduceOutput;\n");
            }
            Reducer::Custom { code: custom_code } => {
                code.push_str(&format!("  const result = {};\n", custom_code));
            }
            Reducer::Activity { activity_name } => {
                code.push_str(&format!(
                    "  const result = await activities.{}(mapResults);\n",
                    activity_name
                ));
            }
        }

        // Return result
        code.push_str(&format!(
            r#"
  return {{
    result,
    processedCount: items.length - failedCount,
    failedCount,
    errors,
  }};
}}
"#
        ));

        // Add helper function for batch processing
        if self.batch_size.is_some() {
            code.push_str(&format!(
                r#"
async function mapBatch<TInput, TOutput>(batch: TInput[]): Promise<TOutput[]> {{
  return Promise.all(batch.map(item => {}));
}}
"#,
                self.map.mapper.to_typescript()
            ));
        }

        code
    }
}

impl Default for MapReduceDefinition {
    fn default() -> Self {
        Self::new("DefaultMapReduce")
    }
}

/// Configuration for the map phase
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct MapConfig {
    /// The mapper function/activity
    pub mapper: Mapper,

    /// Whether to preserve order
    #[serde(default)]
    pub preserve_order: bool,

    /// Retry count for each map operation
    #[serde(default)]
    pub retry_count: u32,
}

impl MapConfig {
    /// Create map config with activity mapper
    pub fn activity(name: impl Into<String>) -> Self {
        Self {
            mapper: Mapper::activity(name),
            preserve_order: false,
            retry_count: 0,
        }
    }

    /// Preserve result order
    pub fn with_order_preserved(mut self) -> Self {
        self.preserve_order = true;
        self
    }

    /// Set retry count
    pub fn with_retries(mut self, count: u32) -> Self {
        self.retry_count = count;
        self
    }
}

/// Mapper types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum Mapper {
    /// Activity mapper
    Activity {
        activity_name: String,
    },
    /// Child workflow mapper
    ChildWorkflow {
        workflow_type: String,
    },
    /// Inline transform
    Transform {
        expression: String,
    },
    /// Custom code
    Custom {
        code: String,
    },
}

impl Mapper {
    /// Create activity mapper
    pub fn activity(name: impl Into<String>) -> Self {
        Mapper::Activity {
            activity_name: name.into(),
        }
    }

    /// Create transform mapper
    pub fn transform(expression: impl Into<String>) -> Self {
        Mapper::Transform {
            expression: expression.into(),
        }
    }

    /// Generate TypeScript code
    pub fn to_typescript(&self) -> String {
        match self {
            Mapper::Activity { activity_name } => {
                format!("activities.{}(item)", activity_name)
            }
            Mapper::ChildWorkflow { workflow_type } => {
                format!("executeChild('{}', {{ args: [item] }})", workflow_type)
            }
            Mapper::Transform { expression } => expression.clone(),
            Mapper::Custom { code } => code.clone(),
        }
    }
}

impl Default for Mapper {
    fn default() -> Self {
        Mapper::Transform {
            expression: "item".to_string(),
        }
    }
}

/// Configuration for the reduce phase
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ReduceConfig {
    /// The reducer function
    pub reducer: Reducer,

    /// Initial value for reduction
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initial_value: Option<serde_json::Value>,
}

impl ReduceConfig {
    /// Create sum reducer
    pub fn sum() -> Self {
        Self {
            reducer: Reducer::Sum,
            initial_value: Some(serde_json::json!(0)),
        }
    }

    /// Create concat reducer
    pub fn concat() -> Self {
        Self {
            reducer: Reducer::Concat,
            initial_value: Some(serde_json::json!([])),
        }
    }

    /// Create merge reducer
    pub fn merge() -> Self {
        Self {
            reducer: Reducer::Merge,
            initial_value: Some(serde_json::json!({})),
        }
    }

    /// Create activity reducer
    pub fn activity(name: impl Into<String>) -> Self {
        Self {
            reducer: Reducer::Activity {
                activity_name: name.into(),
            },
            initial_value: None,
        }
    }

    /// Create custom reducer
    pub fn custom(code: impl Into<String>) -> Self {
        Self {
            reducer: Reducer::Custom { code: code.into() },
            initial_value: None,
        }
    }
}

/// Reducer types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum Reducer {
    /// Sum all values
    Sum,
    /// Concatenate arrays
    Concat,
    /// Merge objects
    Merge,
    /// Activity reducer
    Activity {
        activity_name: String,
    },
    /// Custom reducer code
    Custom {
        code: String,
    },
}

impl Default for Reducer {
    fn default() -> Self {
        Reducer::Concat
    }
}

// Helper function
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '-' || c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_reduce_builder() {
        let mr = MapReduceDefinition::new("ProcessItems")
            .with_description("Process items in parallel and aggregate")
            .with_map(MapConfig::activity("processItem"))
            .with_reduce(ReduceConfig::sum())
            .with_max_concurrency(5)
            .with_batch_size(100);

        assert_eq!(mr.name, "ProcessItems");
        assert_eq!(mr.max_concurrency, 5);
        assert_eq!(mr.batch_size, Some(100));
    }

    #[test]
    fn test_map_config() {
        let config = MapConfig::activity("transform")
            .with_order_preserved()
            .with_retries(3);

        assert!(config.preserve_order);
        assert_eq!(config.retry_count, 3);
    }

    #[test]
    fn test_reduce_configs() {
        let sum = ReduceConfig::sum();
        assert!(matches!(sum.reducer, Reducer::Sum));

        let concat = ReduceConfig::concat();
        assert!(matches!(concat.reducer, Reducer::Concat));

        let merge = ReduceConfig::merge();
        assert!(matches!(merge.reducer, Reducer::Merge));
    }

    #[test]
    fn test_mapper_typescript() {
        let activity = Mapper::activity("processItem");
        assert!(activity.to_typescript().contains("activities.processItem"));

        let transform = Mapper::transform("item * 2");
        assert_eq!(transform.to_typescript(), "item * 2");
    }

    #[test]
    fn test_map_reduce_to_typescript() {
        let mr = MapReduceDefinition::new("TestMapReduce")
            .with_map(MapConfig::activity("process"))
            .with_reduce(ReduceConfig::sum());

        let ts = mr.to_typescript();

        assert!(ts.contains("TestMapReduceMapReduce"));
        assert!(ts.contains("activities.process"));
        assert!(ts.contains("reduce"));
    }

    #[test]
    fn test_map_reduce_with_batching() {
        let mr = MapReduceDefinition::new("BatchedMR")
            .with_batch_size(50)
            .with_map(MapConfig::activity("process"));

        let ts = mr.to_typescript();

        assert!(ts.contains("batchSize = 50"));
        assert!(ts.contains("mapBatch"));
    }

    #[test]
    fn test_validation() {
        let invalid = MapReduceDefinition::new("Invalid").with_max_concurrency(0);
        assert!(invalid.validate_pattern().is_err());

        let valid = MapReduceDefinition::new("Valid");
        assert!(valid.validate_pattern().is_ok());
    }

    #[test]
    fn test_serialization_roundtrip() {
        let mr = MapReduceDefinition::new("Test")
            .with_map(MapConfig::activity("process"))
            .with_reduce(ReduceConfig::sum());

        let json = serde_json::to_string(&mr).unwrap();
        let restored: MapReduceDefinition = serde_json::from_str(&json).unwrap();

        assert_eq!(mr.name, restored.name);
    }
}
