//! Pipeline Pattern
//!
//! Sequential data transformation:
//! - Chain of processing stages
//! - Data flows through stages in order
//! - Each stage transforms the data
//! - Support for error handling at each stage

use serde::{Deserialize, Serialize};
use validator::Validate;

use super::WorkflowPattern;

/// Pipeline pattern for sequential data transformation
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct PipelineDefinition {
    /// Pipeline name
    #[validate(length(min = 1))]
    pub name: String,

    /// Description
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Pipeline stages in order
    #[validate(length(min = 1, message = "Pipeline requires at least one stage"))]
    pub stages: Vec<PipelineStage>,

    /// Error handling strategy
    #[serde(default)]
    pub error_handling: PipelineErrorHandling,

    /// Whether to track intermediate results
    #[serde(default)]
    pub track_intermediate_results: bool,
}

impl PipelineDefinition {
    /// Create a new pipeline
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            stages: vec![],
            error_handling: PipelineErrorHandling::default(),
            track_intermediate_results: false,
        }
    }

    /// Set description
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Add a stage
    pub fn with_stage(mut self, stage: PipelineStage) -> Self {
        self.stages.push(stage);
        self
    }

    /// Set error handling
    pub fn with_error_handling(mut self, handling: PipelineErrorHandling) -> Self {
        self.error_handling = handling;
        self
    }

    /// Enable intermediate result tracking
    pub fn track_intermediate(mut self) -> Self {
        self.track_intermediate_results = true;
        self
    }

    /// Add activity stage
    pub fn activity(self, name: impl Into<String>) -> Self {
        self.with_stage(PipelineStage::activity(name))
    }
}

impl WorkflowPattern for PipelineDefinition {
    fn pattern_name(&self) -> &'static str {
        "Pipeline"
    }

    fn validate_pattern(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if self.stages.is_empty() {
            errors.push("Pipeline requires at least one stage".to_string());
        }

        for (i, stage) in self.stages.iter().enumerate() {
            if stage.name.is_empty() {
                errors.push(format!("Stage {} has empty name", i));
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    fn to_typescript(&self) -> String {
        let mut code = String::new();

        // Header
        code.push_str(&format!(
            r#"// Pipeline: {}
// {}
// Generated by Rust Workflow Compiler

import {{ proxyActivities }} from '@temporalio/workflow';

interface PipelineResult<T> {{
  output: T;
  stagesCompleted: string[];
  intermediateResults?: Record<string, unknown>;
}}

/**
 * {}
 */
export async function {}Pipeline<T>(
  input: unknown
): Promise<PipelineResult<T>> {{
  let currentData = input;
  const stagesCompleted: string[] = [];
"#,
            self.name,
            self.description.as_deref().unwrap_or("No description"),
            self.description.as_deref().unwrap_or(&self.name),
            to_pascal_case(&self.name)
        ));

        if self.track_intermediate_results {
            code.push_str("  const intermediateResults: Record<string, unknown> = {};\n");
        }

        code.push_str("\n");

        // Generate stages
        for stage in &self.stages {
            let stage_name = &stage.name;

            code.push_str(&format!(
                r#"  // Stage: {}
  console.log('Executing stage: {}');
"#,
                stage_name, stage_name
            ));

            // Add retry wrapper if configured
            if stage.retry_count > 0 {
                code.push_str(&format!(
                    r#"  for (let attempt = 0; attempt <= {}; attempt++) {{
    try {{
      currentData = await {};
      break;
    }} catch (error) {{
      if (attempt === {}) throw error;
      console.log(`Stage {} failed, retrying... (attempt ${{attempt + 1}})`);
    }}
  }}
"#,
                    stage.retry_count,
                    stage.processor.to_typescript(),
                    stage.retry_count,
                    stage_name
                ));
            } else {
                code.push_str(&format!(
                    "  currentData = await {};\n",
                    stage.processor.to_typescript()
                ));
            }

            code.push_str(&format!(
                "  stagesCompleted.push('{}');\n",
                stage_name
            ));

            if self.track_intermediate_results {
                code.push_str(&format!(
                    "  intermediateResults['{}'] = currentData;\n",
                    stage_name
                ));
            }

            code.push_str("\n");
        }

        // Return result
        if self.track_intermediate_results {
            code.push_str(
                r#"  return {
    output: currentData as T,
    stagesCompleted,
    intermediateResults,
  };
}
"#,
            );
        } else {
            code.push_str(
                r#"  return {
    output: currentData as T,
    stagesCompleted,
  };
}
"#,
            );
        }

        code
    }
}

impl Default for PipelineDefinition {
    fn default() -> Self {
        Self::new("DefaultPipeline")
    }
}

/// A stage in the pipeline
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct PipelineStage {
    /// Stage name
    #[validate(length(min = 1))]
    pub name: String,

    /// The processor for this stage
    pub processor: StageProcessor,

    /// Number of retries for this stage
    #[serde(default)]
    pub retry_count: u32,

    /// Timeout for this stage (ms)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,

    /// Whether this stage is optional
    #[serde(default)]
    pub optional: bool,

    /// Input transformation before processing
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_transform: Option<String>,

    /// Output transformation after processing
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_transform: Option<String>,
}

impl PipelineStage {
    /// Create a new stage
    pub fn new(name: impl Into<String>, processor: StageProcessor) -> Self {
        Self {
            name: name.into(),
            processor,
            retry_count: 0,
            timeout_ms: None,
            optional: false,
            input_transform: None,
            output_transform: None,
        }
    }

    /// Create an activity stage
    pub fn activity(name: impl Into<String>) -> Self {
        let name = name.into();
        Self::new(name.clone(), StageProcessor::activity(name))
    }

    /// Set retry count
    pub fn with_retries(mut self, count: u32) -> Self {
        self.retry_count = count;
        self
    }

    /// Set timeout
    pub fn with_timeout(mut self, ms: u64) -> Self {
        self.timeout_ms = Some(ms);
        self
    }

    /// Mark as optional
    pub fn optional(mut self) -> Self {
        self.optional = true;
        self
    }

    /// Set input transformation
    pub fn with_input_transform(mut self, transform: impl Into<String>) -> Self {
        self.input_transform = Some(transform.into());
        self
    }

    /// Set output transformation
    pub fn with_output_transform(mut self, transform: impl Into<String>) -> Self {
        self.output_transform = Some(transform.into());
        self
    }
}

/// Processor types for pipeline stages
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum StageProcessor {
    /// Call an activity
    Activity {
        activity_name: String,
        #[serde(default)]
        additional_args: Vec<serde_json::Value>,
    },
    /// Execute child workflow
    ChildWorkflow {
        workflow_type: String,
    },
    /// Local function
    LocalFunction {
        function_name: String,
    },
    /// Inline transformation
    Transform {
        expression: String,
    },
    /// Custom code
    Custom {
        code: String,
    },
}

impl StageProcessor {
    /// Create an activity processor
    pub fn activity(name: impl Into<String>) -> Self {
        StageProcessor::Activity {
            activity_name: name.into(),
            additional_args: vec![],
        }
    }

    /// Create a child workflow processor
    pub fn child_workflow(workflow_type: impl Into<String>) -> Self {
        StageProcessor::ChildWorkflow {
            workflow_type: workflow_type.into(),
        }
    }

    /// Create a transform processor
    pub fn transform(expression: impl Into<String>) -> Self {
        StageProcessor::Transform {
            expression: expression.into(),
        }
    }

    /// Generate TypeScript code
    pub fn to_typescript(&self) -> String {
        match self {
            StageProcessor::Activity {
                activity_name,
                additional_args,
            } => {
                if additional_args.is_empty() {
                    format!("activities.{}(currentData)", activity_name)
                } else {
                    let args: Vec<String> = additional_args
                        .iter()
                        .map(|v| serde_json::to_string(v).unwrap_or_default())
                        .collect();
                    format!(
                        "activities.{}(currentData, {})",
                        activity_name,
                        args.join(", ")
                    )
                }
            }
            StageProcessor::ChildWorkflow { workflow_type } => {
                format!(
                    "executeChild('{}', {{ args: [currentData] }})",
                    workflow_type
                )
            }
            StageProcessor::LocalFunction { function_name } => {
                format!("{}(currentData)", function_name)
            }
            StageProcessor::Transform { expression } => {
                format!("({})", expression)
            }
            StageProcessor::Custom { code } => code.clone(),
        }
    }
}

/// Error handling for pipeline
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum PipelineErrorHandling {
    /// Stop on first error
    #[default]
    StopOnError,
    /// Skip failed stages, continue
    SkipOnError,
    /// Use fallback value on error
    FallbackOnError,
}

// Helper function
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '-' || c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pipeline_builder() {
        let pipeline = PipelineDefinition::new("DataProcessor")
            .with_description("Process data through multiple stages")
            .with_stage(PipelineStage::activity("validate"))
            .with_stage(PipelineStage::activity("transform"))
            .with_stage(PipelineStage::activity("enrich"))
            .track_intermediate();

        assert_eq!(pipeline.name, "DataProcessor");
        assert_eq!(pipeline.stages.len(), 3);
        assert!(pipeline.track_intermediate_results);
    }

    #[test]
    fn test_pipeline_stage_with_retries() {
        let stage = PipelineStage::activity("fetchData")
            .with_retries(3)
            .with_timeout(5000);

        assert_eq!(stage.retry_count, 3);
        assert_eq!(stage.timeout_ms, Some(5000));
    }

    #[test]
    fn test_stage_processor_typescript() {
        let activity = StageProcessor::activity("processItem");
        assert!(activity.to_typescript().contains("activities.processItem"));

        let transform = StageProcessor::transform("currentData.map(x => x * 2)");
        assert!(transform.to_typescript().contains("map"));
    }

    #[test]
    fn test_pipeline_to_typescript() {
        let pipeline = PipelineDefinition::new("TestPipeline")
            .with_stage(PipelineStage::activity("step1"))
            .with_stage(PipelineStage::activity("step2"));

        let ts = pipeline.to_typescript();

        assert!(ts.contains("TestPipelinePipeline"));
        assert!(ts.contains("activities.step1"));
        assert!(ts.contains("activities.step2"));
        assert!(ts.contains("stagesCompleted"));
    }

    #[test]
    fn test_pipeline_with_retries_typescript() {
        let pipeline = PipelineDefinition::new("RetryPipeline")
            .with_stage(PipelineStage::activity("flaky").with_retries(3));

        let ts = pipeline.to_typescript();

        assert!(ts.contains("for (let attempt"));
        assert!(ts.contains("retrying"));
    }

    #[test]
    fn test_validation() {
        let empty = PipelineDefinition::new("Empty");
        assert!(empty.validate_pattern().is_err());

        let valid = PipelineDefinition::new("Valid")
            .with_stage(PipelineStage::activity("step1"));
        assert!(valid.validate_pattern().is_ok());
    }

    #[test]
    fn test_serialization_roundtrip() {
        let pipeline = PipelineDefinition::new("Test")
            .with_stage(PipelineStage::activity("step1"));

        let json = serde_json::to_string(&pipeline).unwrap();
        let restored: PipelineDefinition = serde_json::from_str(&json).unwrap();

        assert_eq!(pipeline.name, restored.name);
        assert_eq!(pipeline.stages.len(), restored.stages.len());
    }
}
