//! Saga Pattern
//!
//! Distributed transactions with compensation logic:
//! - Forward steps with associated compensations
//! - Automatic rollback on failure
//! - Configurable compensation behavior
//! - State tracking for each step

use serde::{Deserialize, Serialize};
use validator::Validate;

use super::WorkflowPattern;

/// Saga definition for distributed transactions with compensation
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct SagaDefinition {
    /// Saga name
    #[validate(length(min = 1, message = "Saga name is required"))]
    pub name: String,

    /// Description of the saga
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Saga steps in execution order
    #[validate(length(min = 1, message = "Saga requires at least one step"))]
    pub steps: Vec<SagaStep>,

    /// Compensation behavior on failure
    #[serde(default)]
    pub compensation_behavior: CompensationBehavior,

    /// Whether to run compensations in parallel
    #[serde(default)]
    pub parallel_compensation: bool,

    /// Maximum time for compensation to complete (ms)
    #[serde(default = "default_compensation_timeout")]
    pub compensation_timeout_ms: u64,
}

fn default_compensation_timeout() -> u64 {
    60000
}

impl SagaDefinition {
    /// Create a new saga definition
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            steps: vec![],
            compensation_behavior: CompensationBehavior::default(),
            parallel_compensation: false,
            compensation_timeout_ms: default_compensation_timeout(),
        }
    }

    /// Add a description
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Add a step
    pub fn with_step(mut self, step: SagaStep) -> Self {
        self.steps.push(step);
        self
    }

    /// Set compensation behavior
    pub fn with_compensation_behavior(mut self, behavior: CompensationBehavior) -> Self {
        self.compensation_behavior = behavior;
        self
    }

    /// Enable parallel compensation
    pub fn parallel_compensation(mut self) -> Self {
        self.parallel_compensation = true;
        self
    }
}

impl WorkflowPattern for SagaDefinition {
    fn pattern_name(&self) -> &'static str {
        "Saga"
    }

    fn validate_pattern(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if self.steps.is_empty() {
            errors.push("Saga requires at least one step".to_string());
        }

        for (i, step) in self.steps.iter().enumerate() {
            if step.name.is_empty() {
                errors.push(format!("Step {} has empty name", i));
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    fn to_typescript(&self) -> String {
        let mut code = String::new();

        // Header
        code.push_str(&format!(
            r#"// Saga: {}
// {}
// Generated by Rust Workflow Compiler

import {{ proxyActivities, ApplicationFailure, sleep }} from '@temporalio/workflow';

interface SagaContext {{
  completedSteps: string[];
  results: Record<string, unknown>;
  errors: Record<string, Error>;
}}

/**
 * {}
 */
export async function {}Saga(input: unknown): Promise<unknown> {{
  const context: SagaContext = {{
    completedSteps: [],
    results: {{}},
    errors: {{}},
  }};

  try {{
"#,
            self.name,
            self.description.as_deref().unwrap_or("No description"),
            self.description.as_deref().unwrap_or(&self.name),
            to_pascal_case(&self.name)
        ));

        // Generate forward steps
        for step in &self.steps {
            code.push_str(&format!(
                r#"    // Step: {}
    console.log('Executing step: {}');
    const {}Result = await {};
    context.completedSteps.push('{}');
    context.results['{}'] = {}Result;

"#,
                step.name,
                step.name,
                to_camel_case(&step.name),
                step.action.to_typescript(),
                step.name,
                step.name,
                to_camel_case(&step.name)
            ));
        }

        code.push_str("    return context.results;\n");
        code.push_str("  } catch (error) {\n");

        // Generate compensation logic
        if self.parallel_compensation {
            code.push_str(
                r#"    // Compensate in parallel
    console.log('Saga failed, compensating in parallel...');
    await Promise.allSettled(
      context.completedSteps.map(stepName => compensateStep(stepName, context, input))
    );
"#,
            );
        } else {
            code.push_str(
                r#"    // Compensate in reverse order
    console.log('Saga failed, compensating in reverse order...');
    for (const stepName of [...context.completedSteps].reverse()) {
      try {
        await compensateStep(stepName, context, input);
      } catch (compensationError) {
        console.error(`Compensation failed for ${stepName}:`, compensationError);
        context.errors[stepName] = compensationError as Error;
      }
    }
"#,
            );
        }

        code.push_str("    throw error;\n");
        code.push_str("  }\n");
        code.push_str("}\n\n");

        // Generate compensateStep function
        code.push_str("async function compensateStep(\n");
        code.push_str("  stepName: string,\n");
        code.push_str("  context: SagaContext,\n");
        code.push_str("  input: unknown\n");
        code.push_str("): Promise<void> {\n");
        code.push_str("  switch (stepName) {\n");

        for step in &self.steps {
            if let Some(compensation) = &step.compensation {
                code.push_str(&format!(
                    "    case '{}':\n      console.log('Compensating: {}');\n      await {};\n      break;\n",
                    step.name,
                    step.name,
                    compensation.to_typescript()
                ));
            }
        }

        code.push_str("    default:\n");
        code.push_str("      console.log(`No compensation defined for ${stepName}`);\n");
        code.push_str("  }\n");
        code.push_str("}\n");

        code
    }
}

impl Default for SagaDefinition {
    fn default() -> Self {
        Self::new("DefaultSaga")
    }
}

/// A step in a saga
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct SagaStep {
    /// Step name
    #[validate(length(min = 1, message = "Step name is required"))]
    pub name: String,

    /// Forward action to execute
    pub action: SagaAction,

    /// Compensation action (rollback)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compensation: Option<SagaAction>,

    /// Error types that should skip compensation
    #[serde(default)]
    pub skip_compensation_errors: Vec<String>,

    /// Whether this step is optional (saga continues on failure)
    #[serde(default)]
    pub optional: bool,
}

impl SagaStep {
    /// Create a new saga step
    pub fn new(name: impl Into<String>, action: SagaAction) -> Self {
        Self {
            name: name.into(),
            action,
            compensation: None,
            skip_compensation_errors: vec![],
            optional: false,
        }
    }

    /// Set compensation action
    pub fn with_compensation(mut self, compensation: SagaAction) -> Self {
        self.compensation = Some(compensation);
        self
    }

    /// Add error type to skip compensation
    pub fn skip_compensation_for(mut self, error_type: impl Into<String>) -> Self {
        self.skip_compensation_errors.push(error_type.into());
        self
    }

    /// Mark step as optional
    pub fn optional(mut self) -> Self {
        self.optional = true;
        self
    }
}

/// Action type for saga steps
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum SagaAction {
    /// Call an activity
    Activity {
        activity_name: String,
        #[serde(default)]
        input: serde_json::Value,
    },
    /// Execute a child workflow
    ChildWorkflow {
        workflow_type: String,
        #[serde(default)]
        input: serde_json::Value,
    },
    /// Call a local activity
    LocalActivity {
        function_name: String,
        #[serde(default)]
        input: serde_json::Value,
    },
    /// Custom TypeScript code
    Custom { code: String },
}

impl SagaAction {
    /// Create an activity action
    pub fn activity(name: impl Into<String>) -> Self {
        SagaAction::Activity {
            activity_name: name.into(),
            input: serde_json::Value::Object(Default::default()),
        }
    }

    /// Create an activity action with input
    pub fn activity_with_input(name: impl Into<String>, input: serde_json::Value) -> Self {
        SagaAction::Activity {
            activity_name: name.into(),
            input,
        }
    }

    /// Create a child workflow action
    pub fn child_workflow(workflow_type: impl Into<String>) -> Self {
        SagaAction::ChildWorkflow {
            workflow_type: workflow_type.into(),
            input: serde_json::Value::Object(Default::default()),
        }
    }

    /// Create a custom code action
    pub fn custom(code: impl Into<String>) -> Self {
        SagaAction::Custom { code: code.into() }
    }

    /// Generate TypeScript code for this action
    pub fn to_typescript(&self) -> String {
        match self {
            SagaAction::Activity {
                activity_name,
                input,
            } => {
                let input_str = if input.is_object() && input.as_object().unwrap().is_empty() {
                    "input".to_string()
                } else {
                    serde_json::to_string(input).unwrap_or_else(|_| "{}".to_string())
                };
                format!("activities.{}({})", activity_name, input_str)
            }
            SagaAction::ChildWorkflow {
                workflow_type,
                input,
            } => {
                let input_str = if input.is_object() && input.as_object().unwrap().is_empty() {
                    "input".to_string()
                } else {
                    serde_json::to_string(input).unwrap_or_else(|_| "{}".to_string())
                };
                format!("executeChild('{}', {{ args: [{}] }})", workflow_type, input_str)
            }
            SagaAction::LocalActivity {
                function_name,
                input,
            } => {
                let input_str = if input.is_object() && input.as_object().unwrap().is_empty() {
                    "input".to_string()
                } else {
                    serde_json::to_string(input).unwrap_or_else(|_| "{}".to_string())
                };
                format!("localActivities.{}({})", function_name, input_str)
            }
            SagaAction::Custom { code } => code.clone(),
        }
    }
}

/// Compensation behavior when a saga step fails
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum CompensationBehavior {
    /// Compensate all completed steps on failure
    #[default]
    CompensateAll,
    /// Compensate only the failed step
    CompensateFailed,
    /// No automatic compensation
    NoCompensation,
    /// Custom compensation logic
    Custom,
}

// Helper functions
fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for (i, c) in s.chars().enumerate() {
        if c == '-' || c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else if i == 0 {
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }

    result
}

fn to_pascal_case(s: &str) -> String {
    let camel = to_camel_case(s);
    let mut chars = camel.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_saga_definition_builder() {
        let saga = SagaDefinition::new("OrderSaga")
            .with_description("Process order with compensation")
            .with_step(
                SagaStep::new("reserveInventory", SagaAction::activity("reserveInventory"))
                    .with_compensation(SagaAction::activity("releaseInventory")),
            )
            .with_step(
                SagaStep::new("chargePayment", SagaAction::activity("chargePayment"))
                    .with_compensation(SagaAction::activity("refundPayment")),
            );

        assert_eq!(saga.name, "OrderSaga");
        assert_eq!(saga.steps.len(), 2);
        assert!(saga.steps[0].compensation.is_some());
    }

    #[test]
    fn test_saga_step_optional() {
        let step = SagaStep::new("notifyUser", SagaAction::activity("sendNotification")).optional();

        assert!(step.optional);
    }

    #[test]
    fn test_saga_action_to_typescript() {
        let activity = SagaAction::activity("processPayment");
        assert!(activity.to_typescript().contains("activities.processPayment"));

        let child_workflow = SagaAction::child_workflow("SubProcess");
        assert!(child_workflow.to_typescript().contains("executeChild"));
    }

    #[test]
    fn test_saga_to_typescript() {
        let saga = SagaDefinition::new("TestSaga")
            .with_step(SagaStep::new("step1", SagaAction::activity("doStep1")));

        let ts = saga.to_typescript();

        assert!(ts.contains("TestSagaSaga"));
        assert!(ts.contains("activities.doStep1"));
        assert!(ts.contains("compensateStep"));
    }

    #[test]
    fn test_saga_parallel_compensation() {
        let saga = SagaDefinition::new("ParallelSaga")
            .parallel_compensation()
            .with_step(SagaStep::new("step1", SagaAction::activity("doStep1")));

        let ts = saga.to_typescript();

        assert!(ts.contains("Promise.allSettled"));
    }

    #[test]
    fn test_saga_validation() {
        let empty_saga = SagaDefinition::new("EmptySaga");
        assert!(empty_saga.validate_pattern().is_err());

        let valid_saga = SagaDefinition::new("ValidSaga")
            .with_step(SagaStep::new("step1", SagaAction::activity("doStep1")));
        assert!(valid_saga.validate_pattern().is_ok());
    }

    #[test]
    fn test_serialization_roundtrip() {
        let saga = SagaDefinition::new("TestSaga")
            .with_step(SagaStep::new("step1", SagaAction::activity("doStep1")));

        let json = serde_json::to_string(&saga).unwrap();
        let restored: SagaDefinition = serde_json::from_str(&json).unwrap();

        assert_eq!(saga.name, restored.name);
        assert_eq!(saga.steps.len(), restored.steps.len());
    }
}
