//! Scatter-Gather Pattern
//!
//! Parallel execution with result collection:
//! - Fan out work to multiple workers
//! - Collect and aggregate results
//! - Handle partial failures
//! - Support timeout and threshold completion

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use validator::Validate;

use super::WorkflowPattern;

/// Scatter-Gather pattern for parallel execution
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ScatterGatherDefinition {
    /// Pattern name
    #[validate(length(min = 1))]
    pub name: String,

    /// Description
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The scatter configuration
    pub scatter: ScatterConfig,

    /// The gather configuration
    pub gather: GatherConfig,

    /// Timeout for all workers (ms)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,

    /// Whether to continue gathering after timeout
    #[serde(default)]
    pub partial_results_on_timeout: bool,
}

impl ScatterGatherDefinition {
    /// Create a new scatter-gather definition
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            scatter: ScatterConfig::default(),
            gather: GatherConfig::default(),
            timeout_ms: None,
            partial_results_on_timeout: false,
        }
    }

    /// Set description
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Set scatter config
    pub fn with_scatter(mut self, scatter: ScatterConfig) -> Self {
        self.scatter = scatter;
        self
    }

    /// Set gather config
    pub fn with_gather(mut self, gather: GatherConfig) -> Self {
        self.gather = gather;
        self
    }

    /// Set timeout
    pub fn with_timeout(mut self, ms: u64) -> Self {
        self.timeout_ms = Some(ms);
        self
    }

    /// Allow partial results on timeout
    pub fn allow_partial_on_timeout(mut self) -> Self {
        self.partial_results_on_timeout = true;
        self
    }
}

impl WorkflowPattern for ScatterGatherDefinition {
    fn pattern_name(&self) -> &'static str {
        "ScatterGather"
    }

    fn validate_pattern(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if self.scatter.workers.is_empty() {
            errors.push("Scatter requires at least one worker".to_string());
        }

        if let Some(threshold) = self.gather.threshold {
            if threshold == 0 {
                errors.push("Gather threshold must be greater than 0".to_string());
            }
            if threshold > self.scatter.workers.len() {
                errors.push("Gather threshold cannot exceed number of workers".to_string());
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    fn to_typescript(&self) -> String {
        let mut code = String::new();

        // Header
        code.push_str(&format!(
            r#"// Scatter-Gather: {}
// {}
// Generated by Rust Workflow Compiler

import {{ proxyActivities, CancellationScope }} from '@temporalio/workflow';

interface ScatterGatherResult<T> {{
  results: T[];
  errors: Error[];
  completedCount: number;
  totalCount: number;
}}

/**
 * {}
 */
export async function {}ScatterGather<T>(
  input: unknown
): Promise<ScatterGatherResult<T>> {{
  const workers = [
"#,
            self.name,
            self.description.as_deref().unwrap_or("No description"),
            self.description.as_deref().unwrap_or(&self.name),
            to_pascal_case(&self.name)
        ));

        // Generate worker definitions
        for worker in &self.scatter.workers {
            code.push_str(&format!(
                "    () => {},\n",
                worker.to_typescript()
            ));
        }

        code.push_str("  ];\n\n");

        // Generate execution logic
        if let Some(timeout) = self.timeout_ms {
            code.push_str(&format!(
                r#"  const timeout = {};
  const results: T[] = [];
  const errors: Error[] = [];

  const workerPromises = workers.map(async (worker, index) => {{
    try {{
      const result = await Promise.race([
        worker(),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error('Worker timeout')), timeout)
        ),
      ]) as T;
      return {{ success: true, result, index }};
    }} catch (error) {{
      return {{ success: false, error: error as Error, index }};
    }}
  }});

"#,
                timeout
            ));
        } else {
            code.push_str(
                r#"  const results: T[] = [];
  const errors: Error[] = [];

  const workerPromises = workers.map(async (worker, index) => {
    try {
      const result = await worker() as T;
      return { success: true, result, index };
    } catch (error) {
      return { success: false, error: error as Error, index };
    }
  });

"#,
            );
        }

        // Generate gather logic
        match &self.gather.strategy {
            GatherStrategy::WaitAll => {
                code.push_str(
                    r#"  // Wait for all workers to complete
  const outcomes = await Promise.allSettled(workerPromises);

  for (const outcome of outcomes) {
    if (outcome.status === 'fulfilled') {
      if (outcome.value.success) {
        results.push(outcome.value.result!);
      } else {
        errors.push(outcome.value.error!);
      }
    } else {
      errors.push(new Error(outcome.reason));
    }
  }
"#,
                );
            }
            GatherStrategy::WaitFirst => {
                code.push_str(
                    r#"  // Wait for first successful result
  const firstResult = await Promise.race(
    workerPromises.map(p => p.then(r => {
      if (r.success) return r;
      throw r.error;
    }))
  );

  if (firstResult.success) {
    results.push(firstResult.result!);
  }
"#,
                );
            }
            GatherStrategy::WaitThreshold => {
                let threshold = self.gather.threshold.unwrap_or(1);
                code.push_str(&format!(
                    r#"  // Wait for {} successful results
  let completedCount = 0;
  const threshold = {};

  for await (const result of raceToThreshold(workerPromises, threshold)) {{
    if (result.success) {{
      results.push(result.result!);
      completedCount++;
    }} else {{
      errors.push(result.error!);
    }}
  }}
"#,
                    threshold, threshold
                ));
            }
        }

        // Return result
        code.push_str(&format!(
            r#"
  return {{
    results,
    errors,
    completedCount: results.length,
    totalCount: workers.length,
  }};
}}
"#
        ));

        // Add helper function for threshold gathering
        if matches!(self.gather.strategy, GatherStrategy::WaitThreshold) {
            code.push_str(
                r#"
async function* raceToThreshold<T>(
  promises: Promise<T>[],
  threshold: number
): AsyncGenerator<T> {
  const pending = new Map<number, Promise<{ index: number; value: T }>>();
  let yielded = 0;

  promises.forEach((promise, index) => {
    pending.set(
      index,
      promise.then(value => ({ index, value }))
    );
  });

  while (pending.size > 0 && yielded < threshold) {
    const { index, value } = await Promise.race(pending.values());
    pending.delete(index);
    yielded++;
    yield value;
  }
}
"#,
            );
        }

        code
    }
}

impl Default for ScatterGatherDefinition {
    fn default() -> Self {
        Self::new("DefaultScatterGather")
    }
}

/// Configuration for scattering work
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ScatterConfig {
    /// Workers to execute in parallel
    pub workers: Vec<ScatterWorker>,

    /// Maximum concurrent workers (0 = unlimited)
    #[serde(default)]
    pub max_concurrency: usize,

    /// Input distribution strategy
    #[serde(default)]
    pub distribution: InputDistribution,
}

impl ScatterConfig {
    /// Create scatter config with workers
    pub fn with_workers(workers: Vec<ScatterWorker>) -> Self {
        Self {
            workers,
            max_concurrency: 0,
            distribution: InputDistribution::default(),
        }
    }

    /// Set max concurrency
    pub fn with_max_concurrency(mut self, max: usize) -> Self {
        self.max_concurrency = max;
        self
    }
}

/// A worker in the scatter phase
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum ScatterWorker {
    /// Call an activity
    Activity {
        activity_name: String,
        #[serde(default)]
        input: serde_json::Value,
    },
    /// Execute child workflow
    ChildWorkflow {
        workflow_type: String,
        #[serde(default)]
        input: serde_json::Value,
    },
    /// Custom async function
    Custom { code: String },
}

impl ScatterWorker {
    /// Create an activity worker
    pub fn activity(name: impl Into<String>) -> Self {
        ScatterWorker::Activity {
            activity_name: name.into(),
            input: serde_json::Value::Object(Default::default()),
        }
    }

    /// Create a child workflow worker
    pub fn child_workflow(workflow_type: impl Into<String>) -> Self {
        ScatterWorker::ChildWorkflow {
            workflow_type: workflow_type.into(),
            input: serde_json::Value::Object(Default::default()),
        }
    }

    /// Generate TypeScript code
    pub fn to_typescript(&self) -> String {
        match self {
            ScatterWorker::Activity {
                activity_name,
                input,
            } => {
                let input_str = if input.is_object() && input.as_object().unwrap().is_empty() {
                    "input".to_string()
                } else {
                    serde_json::to_string(input).unwrap_or_else(|_| "{}".to_string())
                };
                format!("activities.{}({})", activity_name, input_str)
            }
            ScatterWorker::ChildWorkflow {
                workflow_type,
                input,
            } => {
                let input_str = if input.is_object() && input.as_object().unwrap().is_empty() {
                    "input".to_string()
                } else {
                    serde_json::to_string(input).unwrap_or_else(|_| "{}".to_string())
                };
                format!(
                    "executeChild('{}', {{ args: [{}] }})",
                    workflow_type, input_str
                )
            }
            ScatterWorker::Custom { code } => code.clone(),
        }
    }
}

/// Input distribution strategy
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum InputDistribution {
    /// Broadcast same input to all workers
    #[default]
    Broadcast,
    /// Split array input among workers
    Partition,
    /// Round-robin distribution
    RoundRobin,
}

/// Configuration for gathering results
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct GatherConfig {
    /// Gathering strategy
    #[serde(default)]
    pub strategy: GatherStrategy,

    /// Number of results needed for threshold strategy
    #[serde(skip_serializing_if = "Option::is_none")]
    pub threshold: Option<usize>,

    /// How to aggregate results
    #[serde(default)]
    pub aggregation: ResultAggregation,

    /// Error handling strategy
    #[serde(default)]
    pub error_handling: ErrorHandling,
}

impl GatherConfig {
    /// Create config that waits for all
    pub fn wait_all() -> Self {
        Self {
            strategy: GatherStrategy::WaitAll,
            ..Default::default()
        }
    }

    /// Create config that waits for first
    pub fn wait_first() -> Self {
        Self {
            strategy: GatherStrategy::WaitFirst,
            ..Default::default()
        }
    }

    /// Create config that waits for threshold
    pub fn wait_threshold(threshold: usize) -> Self {
        Self {
            strategy: GatherStrategy::WaitThreshold,
            threshold: Some(threshold),
            ..Default::default()
        }
    }
}

/// Strategy for gathering results
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum GatherStrategy {
    /// Wait for all workers to complete
    #[default]
    WaitAll,
    /// Return after first success
    WaitFirst,
    /// Return after N successes
    WaitThreshold,
}

/// How to aggregate results
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum ResultAggregation {
    /// Return array of results
    #[default]
    Array,
    /// Merge objects
    Merge,
    /// Custom aggregation function
    Custom,
}

/// Error handling strategy
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum ErrorHandling {
    /// Fail on any error
    FailFast,
    /// Continue and collect errors
    #[default]
    CollectErrors,
    /// Ignore errors
    Ignore,
}

// Helper function
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '-' || c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scatter_gather_builder() {
        let sg = ScatterGatherDefinition::new("ProcessBatch")
            .with_description("Process items in parallel")
            .with_scatter(ScatterConfig::with_workers(vec![
                ScatterWorker::activity("processItem"),
                ScatterWorker::activity("processItem"),
            ]))
            .with_gather(GatherConfig::wait_all())
            .with_timeout(30000);

        assert_eq!(sg.name, "ProcessBatch");
        assert_eq!(sg.scatter.workers.len(), 2);
        assert_eq!(sg.timeout_ms, Some(30000));
    }

    #[test]
    fn test_gather_strategies() {
        let wait_all = GatherConfig::wait_all();
        assert_eq!(wait_all.strategy, GatherStrategy::WaitAll);

        let wait_first = GatherConfig::wait_first();
        assert_eq!(wait_first.strategy, GatherStrategy::WaitFirst);

        let wait_threshold = GatherConfig::wait_threshold(3);
        assert_eq!(wait_threshold.strategy, GatherStrategy::WaitThreshold);
        assert_eq!(wait_threshold.threshold, Some(3));
    }

    #[test]
    fn test_scatter_worker_typescript() {
        let activity = ScatterWorker::activity("processItem");
        assert!(activity.to_typescript().contains("activities.processItem"));

        let child = ScatterWorker::child_workflow("SubProcess");
        assert!(child.to_typescript().contains("executeChild"));
    }

    #[test]
    fn test_scatter_gather_to_typescript() {
        let sg = ScatterGatherDefinition::new("TestGather")
            .with_scatter(ScatterConfig::with_workers(vec![ScatterWorker::activity(
                "doWork",
            )]))
            .with_gather(GatherConfig::wait_all());

        let ts = sg.to_typescript();

        assert!(ts.contains("TestGatherScatterGather"));
        assert!(ts.contains("Promise.allSettled"));
    }

    #[test]
    fn test_validation() {
        let empty = ScatterGatherDefinition::new("Empty");
        assert!(empty.validate_pattern().is_err());

        let invalid_threshold = ScatterGatherDefinition::new("Invalid")
            .with_scatter(ScatterConfig::with_workers(vec![ScatterWorker::activity("work")]))
            .with_gather(GatherConfig::wait_threshold(5)); // More than workers

        assert!(invalid_threshold.validate_pattern().is_err());
    }

    #[test]
    fn test_serialization_roundtrip() {
        let sg = ScatterGatherDefinition::new("Test")
            .with_scatter(ScatterConfig::with_workers(vec![ScatterWorker::activity(
                "work",
            )]));

        let json = serde_json::to_string(&sg).unwrap();
        let restored: ScatterGatherDefinition = serde_json::from_str(&json).unwrap();

        assert_eq!(sg.name, restored.name);
    }
}
