//! API key authentication middleware.
//!
//! Provides SHA-256 based API key validation that is compatible with the
//! TypeScript implementation in `apps/workflow-builder/src/lib/security/`.
//! Keys are hashed before comparison so that raw secrets are never stored.

use axum::http::request::Parts;
use axum::http::StatusCode;
use axum::Json;
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// ---------------------------------------------------------------------------
// Authenticated user context
// ---------------------------------------------------------------------------

/// Represents a successfully authenticated user extracted from a valid API key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthenticatedUser {
    pub user_id: String,
    pub project_id: Option<String>,
    pub key_id: String,
}

// ---------------------------------------------------------------------------
// API key record (Supabase row shape)
// ---------------------------------------------------------------------------

/// A row from the `api_keys` Supabase table.
#[derive(Debug, Clone, Deserialize)]
pub struct ApiKeyRecord {
    pub id: String,
    pub user_id: String,
    pub project_id: Option<String>,
    pub key_hash: String,
    pub is_active: bool,
    pub expires_at: Option<String>,
}

// ---------------------------------------------------------------------------
// Auth error type
// ---------------------------------------------------------------------------

/// Structured authentication error returned as JSON.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthError {
    pub code: String,
    pub message: String,
}

impl AuthError {
    /// The request did not include an API key at all.
    pub fn missing_key() -> (StatusCode, Json<AuthError>) {
        (
            StatusCode::UNAUTHORIZED,
            Json(AuthError {
                code: "MISSING_API_KEY".to_string(),
                message: "Authorization header with Bearer token is required".to_string(),
            }),
        )
    }

    /// The provided API key could not be validated (wrong hash, inactive, expired).
    pub fn invalid_key() -> (StatusCode, Json<AuthError>) {
        (
            StatusCode::UNAUTHORIZED,
            Json(AuthError {
                code: "INVALID_API_KEY".to_string(),
                message: "The provided API key is invalid or expired".to_string(),
            }),
        )
    }
}

// ---------------------------------------------------------------------------
// Hashing
// ---------------------------------------------------------------------------

/// Produce a lowercase hex SHA-256 digest of the given API key.
///
/// This **must** produce identical output to the TypeScript implementation so
/// that keys generated by the web app can be validated by the Rust service.
pub fn hash_api_key(key: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(key.as_bytes());
    let result = hasher.finalize();
    // Format each byte as two lowercase hex characters (64 chars total).
    result.iter().map(|b| format!("{b:02x}")).collect()
}

// ---------------------------------------------------------------------------
// Bearer token extraction
// ---------------------------------------------------------------------------

/// Extract the bearer token from the `Authorization` header.
///
/// Returns `None` when the header is absent or uses a scheme other than
/// `Bearer` (case-insensitive prefix match).
pub fn extract_bearer_token(parts: &Parts) -> Option<String> {
    let header_value = parts.headers.get("authorization")?.to_str().ok()?;

    // Must start with "Bearer " (case-insensitive scheme).
    let prefix = "Bearer ";
    if header_value.len() <= prefix.len() {
        return None;
    }
    if !header_value[..prefix.len()].eq_ignore_ascii_case(prefix) {
        return None;
    }

    let token = header_value[prefix.len()..].trim();
    if token.is_empty() {
        return None;
    }
    Some(token.to_string())
}

// ---------------------------------------------------------------------------
// Key validation
// ---------------------------------------------------------------------------

/// Validate an API key against the `api_keys` table in Supabase.
///
/// The function hashes the raw key, queries Supabase for a matching active
/// record, checks the expiration timestamp, and returns an `AuthenticatedUser`
/// on success.
///
/// NOTE: The `client` parameter currently accepts a generic `reqwest::Client`
/// because the `SupabaseClient` abstraction is being built in parallel. Once
/// that lands this signature will be updated to accept `&SupabaseClient`.
pub async fn validate_api_key(
    client: &reqwest::Client,
    supabase_url: &str,
    supabase_service_key: &str,
    api_key: &str,
) -> Result<AuthenticatedUser, (StatusCode, Json<AuthError>)> {
    let hashed = hash_api_key(api_key);

    // Query the api_keys table via Supabase REST API.
    let url = format!(
        "{}/rest/v1/api_keys?key_hash=eq.{}&is_active=eq.true&select=id,user_id,project_id,key_hash,is_active,expires_at",
        supabase_url.trim_end_matches('/'),
        hashed,
    );

    let response = client
        .get(&url)
        .header("apikey", supabase_service_key)
        .header("Authorization", format!("Bearer {supabase_service_key}"))
        .header("Accept", "application/json")
        .send()
        .await
        .map_err(|e| {
            tracing::error!("Supabase request failed during API key validation: {e}");
            AuthError::invalid_key()
        })?;

    if !response.status().is_success() {
        tracing::error!(
            "Supabase returned non-success status {} during API key validation",
            response.status()
        );
        return Err(AuthError::invalid_key());
    }

    let records: Vec<ApiKeyRecord> = response.json().await.map_err(|e| {
        tracing::error!("Failed to deserialize api_keys response: {e}");
        AuthError::invalid_key()
    })?;

    let record = records.into_iter().next().ok_or_else(AuthError::invalid_key)?;

    // Check expiration if set.
    if let Some(ref expires_at) = record.expires_at {
        let expiry = chrono::DateTime::parse_from_rfc3339(expires_at).map_err(|e| {
            tracing::error!("Invalid expires_at format: {e}");
            AuthError::invalid_key()
        })?;

        if expiry < Utc::now() {
            tracing::warn!("API key {} has expired", record.id);
            return Err(AuthError::invalid_key());
        }
    }

    Ok(AuthenticatedUser {
        user_id: record.user_id,
        project_id: record.project_id,
        key_id: record.id,
    })
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::{HeaderMap, HeaderValue, Method, Uri};

    // -----------------------------------------------------------------------
    // Helper: build Parts from headers
    // -----------------------------------------------------------------------

    fn make_parts(headers: HeaderMap) -> Parts {
        let mut request = axum::http::Request::builder()
            .method(Method::GET)
            .uri(Uri::from_static("http://localhost/test"))
            .body(())
            .unwrap();
        *request.headers_mut() = headers;
        request.into_parts().0
    }

    // -----------------------------------------------------------------------
    // hash_api_key tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_hash_api_key_produces_64_char_hex() {
        let hash = hash_api_key("sk_live_test_key_123");
        assert_eq!(hash.len(), 64, "SHA-256 hex digest must be 64 characters");
        assert!(
            hash.chars().all(|c| c.is_ascii_hexdigit()),
            "Hash must contain only hex characters"
        );
        // Must be lowercase.
        assert_eq!(hash, hash.to_lowercase(), "Hash must be lowercase hex");
    }

    #[test]
    fn test_hash_api_key_deterministic() {
        let hash1 = hash_api_key("sk_live_deterministic_test");
        let hash2 = hash_api_key("sk_live_deterministic_test");
        assert_eq!(hash1, hash2, "Same input must produce the same hash");
    }

    #[test]
    fn test_hash_api_key_different_inputs_different_hashes() {
        let hash_a = hash_api_key("sk_live_key_alpha");
        let hash_b = hash_api_key("sk_live_key_beta");
        assert_ne!(
            hash_a, hash_b,
            "Different inputs must produce different hashes"
        );
    }

    // -----------------------------------------------------------------------
    // extract_bearer_token tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_extract_bearer_token_valid() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "authorization",
            HeaderValue::from_static("Bearer sk_live_abc123"),
        );
        let parts = make_parts(headers);
        let token = extract_bearer_token(&parts);
        assert_eq!(token, Some("sk_live_abc123".to_string()));
    }

    #[test]
    fn test_extract_bearer_token_missing_header() {
        let parts = make_parts(HeaderMap::new());
        assert_eq!(extract_bearer_token(&parts), None);
    }

    #[test]
    fn test_extract_bearer_token_wrong_scheme() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "authorization",
            HeaderValue::from_static("Basic dXNlcjpwYXNz"),
        );
        let parts = make_parts(headers);
        assert_eq!(
            extract_bearer_token(&parts),
            None,
            "Non-Bearer schemes must return None"
        );
    }

    #[test]
    fn test_extract_bearer_token_empty_token() {
        let mut headers = HeaderMap::new();
        headers.insert("authorization", HeaderValue::from_static("Bearer "));
        let parts = make_parts(headers);
        assert_eq!(
            extract_bearer_token(&parts),
            None,
            "Empty token after Bearer must return None"
        );
    }

    #[test]
    fn test_extract_bearer_token_case_insensitive_scheme() {
        let mut headers = HeaderMap::new();
        headers.insert(
            "authorization",
            HeaderValue::from_static("bearer sk_live_lower"),
        );
        let parts = make_parts(headers);
        assert_eq!(
            extract_bearer_token(&parts),
            Some("sk_live_lower".to_string()),
            "Bearer scheme should be case-insensitive"
        );
    }
}
